### ISSUE TITLE
Unhandled exception in  GetNewRelsID(XMLNode relationshipsNode)

### ISSUE THREAD

**Issue by anfedotoff** [troldal/OpenXLSX#139]
Hi,
I was playing with libFuzzer and found crash when opening xlsx-file with `OpenXLSX::XLDocument::open` function.

Exception occurs when opening [crash-ad6cb54a3483fbd8f99651e4d010510e5cac3b36.txt](https://github.com/troldal/OpenXLSX/files/8325055/crash-ad6cb54a3483fbd8f99651e4d010510e5cac3b36.txt) file. You can use docker and fuzz targets from [oss-sydr-fuzz](https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/openxlsx) to reproduce error:

    /fuzzer ./crash-ad6cb54a3483fbd8f99651e4d010510e5cac3b36.txt

Libfuzzer's output:

```Running: ./crash-ad6cb54a3483fbd8f99651e4d010510e5cac3b36.txt
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 3) > this->size() (which is 0)
==24== ERROR: libFuzzer: deadly signal
    #0 0x4e1ba1 in __sanitizer_print_stack_trace /llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
    #1 0x4564d7 in fuzzer::PrintStackTrace() /llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    #2 0x43c813 in fuzzer::Fuzzer::CrashCallback() /llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:233:3
    #3 0x7faba64823bf  (/lib/x86_64-linux-gnu/libpthread.so.0+0x153bf)
    #4 0x7faba629318a in __libc_signal_restore_set /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h:86:3
    #5 0x7faba629318a in raise /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:48:3
    #6 0x7faba6272858 in abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:79:7
    #7 0x7faba667d910  (/lib/x86_64-linux-gnu/libstdc++.so.6+0x9e910)
    #8 0x7faba668938b  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xaa38b)
    #9 0x7faba66893f6 in std::terminate() (/lib/x86_64-linux-gnu/libstdc++.so.6+0xaa3f6)
    #10 0x7faba66896a8 in __cxa_throw (/lib/x86_64-linux-gnu/libstdc++.so.6+0xaa6a8)
    #11 0x7faba66803aa  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xa13aa)
    #12 0x7faba6724f47 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const (/lib/x86_64-linux-gnu/libstdc++.so.6+0x145f47)
    #13 0x56a44c in (anonymous namespace)::GetNewRelsID(pugi::xml_node) /openxlsx/OpenXLSX/sources/XLRelationships.cpp:172:48
    #14 0x568b1a in OpenXLSX::XLRelationships::addRelationship(OpenXLSX::XLRelationshipType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /openxlsx/OpenXLSX/sources/XLRelationships.cpp:272:45
    #15 0x52be46 in OpenXLSX::XLDocument::execCommand(OpenXLSX::XLCommand const&) /openxlsx/OpenXLSX/sources/XLDocument.cpp:822:36
    #16 0x525ee9 in OpenXLSX::XLDocument::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /openxlsx/OpenXLSX/sources/XLDocument.cpp:460:9
    #17 0x510ee9 in LLVMFuzzerTestOneInput /fuzzer.cc:37:13
    #18 0x43dd41 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #19 0x42835c in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #20 0x42e0cb in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #21 0x456e12 in main /llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #22 0x7faba62740b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #23 0x422c7d in _start (/fuzzer+0x422c7d)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal```

**Comment by troldal** [comment]
Hello @anfedotoff 

I'm not so familiar with fuzz testing and libFuzzer. From the above dump, it is not clear what the error message really is. In the code you link to it seems that an Excel spreadsheet is generated is automatically and fed to OpenXLSX. But are you sure that the generated files are valid Excel files?

An sorry, but I'm not going to set up docker just for this :)
